### ISSUE TITLE
Can't run for a simple alert

### ISSUE THREAD

**Issue by modanesh** [timelyart/Kairos#106]
I want to run a simple alert. It logs into the tradingview but stops there. I have a free TV account, and created the chart on AAPL stock. I also manually added an alert `AAPL Test` on the website for crossing a certain price. Here is the alert file I created:

```
charts:
- url: https://www.tradingview.com/chart/yzgdvopg/
  timeframes: [1 day]
  watchlists: ["My Watchlist"]
  alerts:
  - name: "AAPL Test"
    show_multi_chart_layout: no
    include_screenshots_of_charts: ["https://www.tradingview.com/chart/yzgdvopg/"]
    conditions: ["Crossing"]
    trigger: "Only Once"
    expiration:
      time: 5
      open-ended: no
    show_popup: no
    sound:
      play: no
      ringtone: Chirpy
      duration: Once
    send:
      email: yes
      email-to-sms: no
      notify-on-app: no
    message:
      prepend: no
      text: "%NAME %TIMEFRAME: %SYMBOL\n%CHART\n%SCREENSHOT\n%GENERATED"
summary:
  email:
    to: ["myemail@gmail.com"]
    subject: "TradingView Alert Summary"
    text: "My signals: %SUMMARY"
    html: "<p>My signals</p> %SUMMARY"
    send: yes
    one-mail-per-recipient: yes
  watchlist:
    name: "signals_%DATE_%TIME"
    import: no
    attach-to-email: yes
webdriver:
  run-in-background: no

```

here is a screenshot that's saved in the `log` folder:
![20230418_092804](https://user-images.githubusercontent.com/13287048/232686447-ca7e0cbb-b152-460a-b95d-0bcf47b3c048.png)
