### ISSUE TITLE
Screenshots in background not working after upgrade

### ISSUE THREAD

**Issue by alexpunct** [timelyart/Kairos#16]
It seems after I upgraded to the last version that even though it's set to run in the background, when finishing and generating the summary, it's opening the browser in order to take the screenshots (before it was doing that in the background too).

**Comment by timelyart** [comment]
Can you post the summary configuration from the YAML file?

**Comment by alexpunct** [comment]
```yaml
summary:
  # Create email
  email:
    # List of comma separated values
    to: ['nofomopls@gmail.com']
    # List of comma separated values
    # cc: ['my_cc@example.com', 'my_cc_alias@example.com']
    # List of comma separated values
    # Note: not all email providers support bcc (e.g. gmail)
    bcc: []
    subject: 'Alerts Summary - 4h TRI Setups'
    # Use keyword %SUMMARY in your text and/or html to include the Kairos generated summary
    text: '%SUMMARY'
    # Note: you may include <html> and <body> tags but it is not necessary (Kairos will include them if they aren't found)
    html: '<p><strong>Watchlists:</strong> Binance USDT pairs, Binance BTC pairs, Bitmex perpetual pairs (XBT, ETH)<br>
<strong>Alerts timeframe:</strong> 4 hours<br>
<strong>Setups:</strong> El Tangonator, BOT<br>
If you are not familiar with the setups, you can join the community by <a href="https://www.therationalinvestor.com/?ref=F7qfmveLCidGDeDxBh7RUmk" alt="TRI">clicking here</a><br><br>
 %SUMMARY<em>To unsubscribe reply to this email with the text Unsubscribe.</em>'
    # If you just want to send the signals to webhooks (see your config file) or import them as a watchlist, set this to no
    send: yes
    # if you want to shield recipients from seeing each other's email address, set this to yes
    one-mail-per-recipient: yes
```
