### ISSUE TITLE
Browse.yaml

### ISSUE THREAD

**Issue by mupsje** [timelyart/Kairos#96]
**Describe the bug**
When started , all works perfect, then it runs through the charts as a ferrari :)

<img width="835" alt="image" src="https://user-images.githubusercontent.com/46684538/211512015-f59bcca5-76da-45cd-a851-a4751524c4b3.png">

<img width="424" alt="image" src="https://user-images.githubusercontent.com/46684538/211512076-604ef68d-1f18-4c08-97c3-b073589e2319.png">

**Comment by mupsje** [comment]
also recorded the speed of browsing

https://www.dropbox.com/s/6gvircui2la2ulo/chrome_eHxhGxy0wI.mp4?dl=0

**Comment by mupsje** [comment]
also a recorded one

https://www.dropbox.com/s/i9w0avq0p6ua27y/chrome_QMAXdc3I4u.mp4?dl=0

**Comment by timelyart** [comment]
Which OS and python version are you using? 
Are you running Kairos in the cloud?

You might want to disable hardware acceleration in Chrome, or check this [threat](https://stackoverflow.com/questions/67501093/passthrough-is-not-supported-gl-is-disabled).

**Comment by mupsje** [comment]
Kairos-2.86, python 3.11.1 on Windows 11 (env)
Tried the Threat , still running as a ferrari...

real strange

**Comment by timelyart** [comment]
Ah... I thought your issue was with the _**gpu_init.cc**_ error.

I'll look into it.

**Comment by timelyart** [comment]
The example file has stopped working.

Add the following line to your YAML:
`performance: {wait_until_chart_is_loaded: no}`

Your YAML should be something like this:
```
charts:
- url: https://www.tradingview.com/chart/<your_chart>/
  timeframes: [1 week, 1 day]
  watchlists: [<your_watchlist_name>, <your_second_watchlist_name>]
  # What is the minimum amount of seconds that the market should be in view for?
  delays: {change_symbol: 5}
  # Override default behaviour of waiting until the chart is loaded, so it waits at least 5 seconds for each market.
  performance: {wait_until_chart_is_loaded: no}
  alerts: {}
```

The [example file](https://github.com/timelyart/Kairos/blob/master/yaml/_browse.yaml) has been updated as well. 

Thank you for sharing your issue. If this issue still persist feel free to re-open the issue.
